on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: write
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: sshnaidm/gpt-code-review-action@debug
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          post-if-error: 'true'
          # model: 'text-davinci-003'
          # prompt: 'You are helpful assistant is here to review the code. Please review the code change below and provide feedback.'
