name: Watson Code Review

on: [pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: sshnaidm/wca-code-review-action@v1
        with:
          wca-key: ${{ secrets.IAM_APIKEY }}
